package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
	name = "strategy_config_proto",
	protos = [
		"strategy_config.proto",
	],
	with_grpc = True, 
)