package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
	name = "event_scheduler_config_proto",
	protos = ["event_scheduler_config.proto"],
	with_grpc = True,
)