package(default_visibility = ["//visibility:public"])

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cc_proto_library")

cc_proto_library(
	name = "order_proto", 
	protos = ["order.proto"],
	with_grpc = True, 
)
